### ISSUE TITLE
Make a switch cheat code for an address in BASE, is it possible and if so how? 

### ISSUE THREAD

**Issue by ZzzDave** [ReclaimerShawn/My-Programs#14]

**Comment by ReclaimerShawn** [comment]
You have to create a Pointer Code. A BASE Address should have a pointer address found in MAIN or Static HEAP (most likely MAIN). I haven't done this yet due to a combination of being overworked and being lazy when I'm not overworked, but I need to eventually make a video on nothing but pointer creation.
